# -*- coding: utf-8 -*-
"""POS Tagging based on Heuristics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yEEKm85X9R2HEA52829shu0Ipd8__9T8

##Import necessary Libraries
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from nltk.chunk import ne_chunk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

"""## A sentence under consideration for Information Extraction (NER)"""

sentence = 'Virat Kohli is an Indian cricketer who currently captains the India national team. A right-handed top-order batsman, Kohli is regarded as one of the best batsmen in the world'

"""## Apply word tokenization and part-of-speech tagging to the sentence"""

def preprocess(sent):
    sent = word_tokenize(sentence) # TOKENIZE THE SENTENCE
    sent = pos_tag(sent)# GET POS TAG OF THE SENTENCE
    return sent

sent = preprocess(sentence)
sent

"""## Plot a Parse Tree"""

pattern = 'NP: {<DT>?<JJ>*<NN>}'
NPChunker = nltk.RegexpParser(pattern) # Regex Parse using the pattern
result = NPChunker.parse(sent)
#result.draw() # Getting an error TclError: no display name and no $DISPLAY environment variable
import svgling
svgling.draw_tree(result)

!pip install svgling

"""## POS Tags"""

from nltk.chunk import conlltags2tree, tree2conlltags
from pprint import pprint
iob_tagged = tree2conlltags(result)
pprint(iob_tagged)

"""**This is how Information is extracted using heuristics based techniques. Try using another pattern.**"""

